version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:1340
      VITE_LOG_API_URL: http://localhost:4000

  backend:
    build: ./my-strapi-backend
    ports:
      - "1340:1340"
    volumes:
      - ./my-strapi-backend:/app
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: strapi
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      NODE_ENV: development
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"

  quiz-logs-api:
    build: ./quiz-logs-api
    ports:
      - "4000:4000"
    volumes:
      - ./quiz-logs-api:/app
    environment:
      MONGODB_URI: mongodb://mongodb:27017/quiz-logs
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
